package tui

// bannerTips 启动 Banner 随机展示的使用小技巧（程序启动时抽取一条并固定）。
var bannerTips = []string{
	// 2.0.5 报告、聊天回投与桌面
	"每次对话同时留下 Markdown 报告和 .evidence.jsonl，证据按 SHA256 串成链",
	"报告按步骤标风险等级和是否经你确认；取消或失败会写明会话未完成",
	"聊天高危确认只认「允许本次 / 本会话同类 / 本次会话允许所有高危操作 / 拒绝」",
	"确认期间发别的话只会收到提醒，不会另开任务；10 分钟没回复按拒绝",
	"在 QQ、微信、钉钉、企业微信或飞书里建的定时任务，到点发回原来的对话",
	"只在当前聊天发一句话时带 reply_text，不必再开无人值守 Agent",
	"微信长任务跟着你最新一条消息回复；旧凭据失效后再发一句即可补上",
	"QQ 被动回复窗口过期后，结果会改发一次主动消息",
	"电脑操作前先跑 --computer-check；macOS 缺权限时会弹出授权框",
	"同一应用换了窗口要重新截图，避免点到另一个窗口",
	"--batch 不会自动点鼠标键盘，桌面输入仍要单独确认",
	"子任务和主任务共用同一块桌面，不会互相报被占用",
	"网页优先鹰眼，本机窗口才用 computer_use；能用命令就不用鼠标",

	// 聊天与巡检
	"SSH/CMD 使用 --chat-setup-cli 配置机器人、查看连接状态和解绑",
	"图片验证码无法识别时，可通过机器人收图并回复验证码，原任务继续",
	"用鹰眼巡检后直接说「生成报告」，会出带封面和截图的 Word，不必写 JSON 或装 pandoc",
	"Word 巡检报告先写结论，再写详情和建议；截图跟在对应章节后面",
	"inspection_run action=report 会自动找最新会话报告和真实截图",
	"确认操作：Y 本次，A 会话同类，S 本次会话允许所有高危操作",
	"启动面板「聊天」一行显示已启用的微信、QQ、企业微信、飞书等机器人",
	"已配置聊天通道时启动 DeepSentry 会自动拉起机器人，退出 TUI 一并停止",
	"对机器人说「重启会话」开新上下文，说「切换会话」可按序号恢复",
	"聊天预算用尽或暂停后直接发「继续」，不必重开任务",
	"微信/QQ/飞书可直接发图片给模型看，排队前会先把附件下载到本地",
	"每日巡检用 schedule_task kind=inspection，到点出 Word 并可推到群里",
	"聊天里的高危操作在同一会话确认，不会再用 --batch 自动放行",

	// 输入与快捷键
	"Tab 聚焦输入框，Enter 发送安全任务",
	"等待补充信息时，输入选项编号即可继续",
	"Agent 缺少信息时会一次只问一个关键问题",
	"任务运行中也可 Tab 输入新指令，Enter 打断并续跑",
	"Esc 退出输入模式，↑↓/jk 滚动日志",
	"Shift+Enter / Alt+Enter 可在输入框内换行",
	"macOS 可直接 ⌘V 粘贴截图，Windows/Linux 用 Ctrl+V",
	"macOS 用 ⌘A 全选、⌘Z 撤销输入；其他系统用 Ctrl+A / Ctrl+Z。Ctrl+U 清空，Ctrl+L 清屏",
	"按 G 快速跳到日志底部",
	"PgUp / PgDown 翻页浏览 Agent 输出",
	"鼠标滚轮可上下滚动日志区域",
	"输入 q 退出 TUI（需先 Esc 退出输入模式）",
	"粘贴千行日志会折叠显示，提交仍是完整内容",
	"中文输入法候选框会贴近底部输入行",

	// 斜杠命令
	"输入 /help 查看全部快捷键与斜杠命令",
	"/new 开启全新任务；/new <任务> 可直接启动",
	"/status 查看连接、模型与运行状态",
	"/cost 查看真实 token 用量，缺失 usage 时显示估算",
	"/clear 清空当前屏幕日志",
	"/model 查看当前 LLM 提供商与模型名",
	"/config 查看配置文件摘要",
	"/sessions 列出可恢复的 checkpoint 会话",
	"/resume <session_id> 在当前 TUI 直接恢复 checkpoint",
	"/tsecbench 进入 TSecBench 跑分模式",
	"/memory list 查看已注入的结构化记忆",
	"/memory clear 一键清空结构化 Memory",
	"/agents clear 清空外部 AGENTS.md（内置默认保留）",
	"/compact 记录上下文整理提示",
	"/memory clues 查看当前会话自动汇聚的 IP、CVE、哈希和路径",
	"/memory clues clear 只清空当前会话线索，不删除长期 Memory",
	"/mcp 可查看、导入和管理 MCP 扩展服务",
	"/mcp status 可看每个已连接 MCP 以及各自暴露了多少工具",
	"/skill 查看已发现的专业 Skill，Agent 也会按需加载",
	"/sudo 把密码验证交给系统终端，密码不进入模型上下文",

	// 模型与长上下文
	"左上角 ctx=表示显式配置，ctx≈表示名称推断或安全默认",
	"右上角 token 是会话累计用量，不是当前上下文窗口",
	"--init 可直接选 64K、128K、256K、512K、1M、2M 或自定义上下文",
	"不确定模型窗口时选自动，DeepSentry 会保留安全余量",
	"本地模型的 context_window_tokens 应对齐 num_ctx / max_model_len",
	"未声明窗口的本地模型先按 32K 安全默认运行",
	"1M 模型按 token 预算长时保留证据，不再固定 60K 字符就压缩",
	"14B/20B/30B 模型会自动使用精简 Prompt 和任务相关工具",
	"70B 本地模型默认使用 balanced 协作与工具预算",
	"巨大日志会按 token 分块摘要，中间证据不再只被首尾截取",
	"摘要失败时仍会保留原始目标、最新修正、核心线索和最近步骤",
	"API 报 context length 超限时会缩减历史并自动重试一次",
	"context_utilization 控制输入窗口使用率，留 0 让 profile 自动分配",
	"reserved_output_tokens 为模型回答与推理预留空间，留 0 自动计算",
	"Native Tool schema 也会计入上下文预算，避免小模型暗中超窗",
	"native_tool_limit 可限制每轮直接暴露的内置工具数量",
	"Runtime v3 已默认启用；仅遇兼容问题时才临时回滚 legacy",
	"配置 models[] fallback，可在 429、超时或服务故障后自动切换模型",

	// 工具发现与参数契约
	"不确定工具参数时，让 Agent 先用 tool_catalog 查看完整用法",
	"tool_catalog name=config_manage 可返回动作、必填字段和可复制示例",
	"内置工具参数会运行时校验，错误会返回合法字段与修正示例",
	"小模型每轮只看核心与任务相关 schema，其余工具仍可按需发现",
	"说“帮我添加 SSH 服务器”，Agent 会用 config_manage 受控写入配置",
	"config_manage 修改 config.yaml 前会自动创建权限受控备份",
	"添加 SSH 目标时 host 和 port 可分开传，避免默认连到 22 端口",
	"列出远程目标请用 fleet_inventory，不要猜 config_manage 的 action",
	"批量执行前先 fleet_inventory，确认名称、协议、标签和端口",
	"target_health_summary 可一次汇总目标的 CPU、内存、磁盘与关键服务",
	"enabled_tools / disabled_tools 可做内置工具白名单与黑名单",
	"MCP 工具与内置工具可并用，优先选有结构化参数契约的路径",
	"可直接导入 Claude Desktop MCP JSON，无需逐个重写 server 配置",
	"FofaMap MCP 连通后走 fofa_account → rules → search，不要 execute fofa_recon.py",
	"产品/OA/VPN 查询先 fofa_rules，原样使用返回的 app=，不要编造",
	"ZIP 解密第一步 zip_password_recover；有掩码用 recover+mask",
	"HawkEye 已连接时浏览网页走 HawkEye，不要再用内置 browser_browse",
	"HawkEye 验证码用 captcha_assist 分析/提交，不要执行页面脚本读图",
	"B 站播放/倍速/全屏先 load_skill(\"bilibili-play\")，合集用 ?p=N",
	"解出 flag{...} 后 finish 提交，不要把它当成 shell 命令 execute",
	"mcp_server_configs 请写 Python 与 mcp_server.py 的绝对路径",
	"/skill only fofamap 可只保留当前需要的一个 Skill",
	"SSH 默认兼容老设备；不需要旧算法时设 ssh_legacy_compat: false",
	"Nuclei 必须先 nuclei_plan，确认一次性令牌后再 nuclei_execute",

	// 多轮与会话
	"任务完成后可直接追问，上下文会自动保留",
	"计划模式: deepsentry --plan \"你的任务\"",
	"--plan 会先澄清关键选择，再写 todo 并继续执行",
	"恢复会话: deepsentry --tui --resume <session_id>",
	"图形选会话: deepsentry --tui --pick-session",
	"列出会话: deepsentry --list-sessions",
	"Ctrl+C 有选区时复制，无选区时停止任务；再按一次强制退出",

	// 子 Agent 与 Fleet
	"按 e 一键展开全部折叠项，再按一次全部折叠",
	"子 Agent 委派适合多机并行排查同一类问题",
	"Fleet 多目标请在任务中指定 target_selector",
	"selector 支持 all、prod、web-01 等标签与名称",
	"fleet_exec / fleet_file 会按真实命令或文件动作动态判险",
	"混合 SSH/Telnet/FTP 目标会按协议自动拆分调度",
	"每台 Fleet 目标会显示 pending/running/ok/error 状态",
	"Fleet selector 可逗号组合名称、host、protocol 和 tag",
	"多机互不依赖的排查方向可用 parallel_tasks 同时委派",
	"子 Agent 会获得主目标、最新修正、TODO 和高信号核心线索",
	"多机同一证据会在核心线索板合并来源，不会被最后一台覆盖",

	// 模式与工具
	"本地模式：工具在控制端本机执行",
	"默认先用目标机原生 Shell，搞不定再调用内置工具",
	"远程 SSH：mem_info、port_listen 等在目标机执行",
	"控制端工具 ping、nmap_scan 从 DeepSentry 进程发起",
	"Native Tool Calling 已启用时可更稳定地调用内置工具",
	"高风险操作按 Y 仅批准本次，A 允许本会话同类操作，S 允许本次会话所有高危操作，N 拒绝",
	"Shell 规则判高后会先由 AI 复核，只有双高危或复核失败才人工确认",
	"2>&1 只合并错误输出，不再被误判为写文件重定向",
	"Batch 模式自动批准操作，仅建议在隔离环境使用",
	"审计报告自动写入 reports/ 目录，启动 Banner 可看到路径",
	"缺少 webhook、阈值或目标范围时，Agent 会暂停等待补充",
	"定时任务通知支持钉钉、飞书和 HTTP 邮件网关",
	"钉钉/飞书加签机器人需要配置对应 secret",
	"在对话里说明周期和要做的事，模型用 task 加 interval_sec 或 run_at 创建定时任务",
	"/schedule 可查看、修改、取消、重置或删除定时任务；聊天里创建的到点发回原对话",
	"定时任务可同时通知钉钉、飞书和 HTTP 邮件网关",
	"browser_browse 可自动打开隔离 Chrome 或无头会话并持续导航，browser_interact 负责确认后的点击和输入",
	"headless_browser 适合一次性 JavaScript 渲染快照，失败会自动降级静态抓取",
	"web_snapshot 可保留页面快照，http_probe 适合快速存活与状态检查",
	"pcap_analyze 可离线统计 DNS、HTTP、TLS SNI、SMB/NTLM 与会话流",
	"sqlite_inspect 可先列表再定向查询，避免盲目导出整库",
	"db_config_audit 可检查 MySQL/PostgreSQL/Redis 等服务的高风险配置",
	"secret_scan 用于查找代码与配置中的 Token、密钥和高风险凭证",
	"大段工具输出会落盘到会话工作区，上下文只保留摘要与路径",
	"高成功率任务写法：目标 + 时间窗 + 只读/可修改 + 证据与输出格式",
	"先要求只读取证和根因判断，确认后再做最小修改与复验",
	"结论要求附命令、关键输出和 artifact 路径，可明显减少幻觉",
	"网络设备先跑完整 display/show，再按异常字段做过滤投影",
	"projection=filtered 不是截断；output_truncated=true 才是字节上限截断",
	"华为/H3C/锐捷可显式配置 device_type，减少命令方言试错",
	"FTP 先列目录和校验目标路径，再下载；临时文件完成后才会原子落盘",
	"FTP/Telnet 默认是明文协议，生产环境优先 SSH/SFTP 或启用证书校验的 FTPS",
	"比赛题先限定 10 分钟与固定交付格式，最后调用答案自检再提交",

	// 任务示例
	"示例：排查目标机内存与监听端口",
	"示例：分析 auth.log / secure 中的暴力破解 IP",
	"示例：审计网络暴露面与异常 outbound 连接",
	"示例：在 Web 目录狩猎 webshell 与可疑 PHP/JSP",
	"示例：检查 cron、systemd 与启动项中的持久化",
	"示例：对比多机相同路径的配置是否被篡改",
	"示例：读取 /var/log/syslog 最近 ERROR 并归纳根因",
	"示例：对可疑进程做 cmdline、fd、网络连接关联分析",

	// CLI 与脚本
	"脚本/CI 建议: deepsentry --no-tui --task \"...\"",
	"JSONL 事件: deepsentry --no-tui --json --task \"...\"",
	"WebShell 场景: deepsentry --webshell --task \"mem_info 摘要\"",
	"首次使用可运行 deepsentry --init 进入配置向导",
	"--init 可选择配置 /tsecbench 跑分模式",
	"指定配置: deepsentry -c /path/to/config.yaml --tui",
	"HTTP 代理启动: deepsentry -proxy http://127.0.0.1:8080 --task \"...\"",
	"SOCKS5 启动: deepsentry -socks5 socks5://127.0.0.1:1080 --task \"...\"",
	"-proxy 与 -socks5 只覆盖本次进程，不会把代理凭据写回 config.yaml",

	// Skills 与 Memory
	"Agent 可按场景加载 Skills（日志分析、取证、漏洞扫描等）",
	"跨会话 Memory 会在有历史时自动注入上下文",
	"说“记一下/记住这个步骤”会触发 Agent 总结并保存 Memory",
	"内置 AGENTS.md 随单二进制注入，外部 AGENTS.md 可选扩展",
	"核心线索板最多保留 48 条高信号证据，并随 checkpoint 恢复",
	"密码、Bearer Token、API Key 与私钥不会进入核心线索板",
	"临时线索留在当前会话，需要跨会话复用时再让 Agent remember",

	// 确认与安全
	"Enter 不会批准高风险操作，必须按 Y 确认",
	"拒绝危险操作时按 N 或 Esc",
	"无人值守请加 -batch，生产环境务必先评估风险",
	"Telnet 可执行设备命令；FTP 支持目录与文件传输，明文 FTP 请仅用于受控网络",

	// 评测与其他
	"Benchmark TUI: go run ./cmd/benchmark/ -c config.yaml --tui",
	"快速门禁: go run ./cmd/benchmark/ -skip-llm -skip-remote",
	"MCP 用 mcp_server_configs 配置；启动 Banner 会列出每个连接的工具数",
	"enabled_tools / disabled_tools 可精确控制内置工具集",
	"max_steps 可在 config.yaml 调整单任务最大推理步数",
	"思考流默认折叠，按 e 可展开 AI 推理与 JSON 动作",
	"Stream 输出完成后会自动折叠为摘要，减少刷屏",
	"目标切换时状态栏会显示当前 @ 主机与协议",
	"委派任务时尽量写清范围：路径、时间窗、成功标准",
	"追问时引用上一步结论，Agent 会继续同一 checkpoint",
	"长任务中断后可 --resume 从上次步数继续，不必重来",
	"看到供应商故障先看 /status 和 trace，再判断重试、failover 或恢复会话",
}
